name: Recent Activities
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  update-readme-with-youtube:
    name: Update README with recent activity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: Readme-Workflows/recent-activity@2.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.RECENT_ACTIVITES }}
        with:
          COMMIT_MSG: 'Update README with the recent activity'
          MAX_LINES: 10

