name: Recent Activities
on:
  schedule:
    # Runs every hour
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-youtube:
    name: Update README with recent activity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.RECENT_ACTIVITES }}
