name: Recent Activities
on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  update-readme-with-youtube:
    name: Update README with recent activity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.RECENT_ACTIVITES }}
        with:
          COMMIT_MSG: 'Update README with the recent activity'
          MAX_LINES: 10

